---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  require_chef_for_busser: false
  manifests_path: manifests
  modules_path: modules

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04

suites:
 - name: default
   provisioner:
     manifest: site.pp
   verifier:
     inspec_tests:
      - test/integration/default
