---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.9

suites:
  - name: default
    run_list:
      - recipe[vim::default]
    attributes:
